### ISSUE TITLE
Session created by the client needs to be deleted when the service is removed. 

### ISSUE THREAD

**Issue by anandnagraj** [SNIA/Swordfish-basic-web-client#11]
Description: The session created when the service is added should be deleted by sending a DELETE request to the respective URI of the session, when the service is removed. This will ensure that there are no orphan sessions in the server and also prevents a DOS attack.

Also, the option of "Remove" on the session resource to remove the session manually does not work.

**Comment by anandnagraj** [comment]
Issue still exists.

**Comment by rahlvers** [comment]
Fixed in #18
