### ISSUE TITLE
Username of basic web client

### ISSUE THREAD

**Issue by anandnagraj** [SNIA/Swordfish-basic-web-client#12]
Description: The current username is snia@gmail.com. It would be better if the username was something more standardized, like swordfish@snia.org.

**Comment by ddeel** [comment]
Does this email address needs to be "live"? If so, we'll need to get it set up ASAP.

**Comment by rahlvers** [comment]
What is the mechanism to change the username /  password?

**Comment by sravanthikalluri19** [comment]
There is no mechanism to change them as they are static (username and password) names  embedded in a local file.

**Comment by rahlvers** [comment]
Let's add a note in the README of where (which file) these credentials are hard-coded.

**Comment by rahlvers** [comment]
Fixed in pull #10
