### ISSUE TITLE
Need to break apart build/start from just start.

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-basic-web-client#13]
How do you start the web client instead of a combined build start?  There's no need to build every time you want to start.

**Comment by sravanthikalluri19** [comment]
Build is not required every time when we start the application. But build is required is changes to any files are made.so, build was integrated with the start.
update: 
1. Build and start are made into two different steps, 
2. Necessary files are modified.
3. Updated Readme file

**Comment by rahlvers** [comment]
Fixed in #10
