### ISSUE TITLE
User interface labels need to be clarified for adding to collections

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-basic-web-client#17]
When adding to collections like StorageServices or Volumes, the user interface shows a new column labeled “Add Collection” that includes a text entry box labeled “Collection Name”.

To make the user interface clearer and more intuitive, the new column should be labeled “Add To Collection” (instead of “Add Collection”) and the text entry box should be labeled “Name” (instead of “Collection Name”).

**Comment by rahlvers** [comment]
Fixed in #18
