### ISSUE TITLE
Unable to edit the writeable properties of some objects

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-basic-web-client#20]
The writeable properties of objects under StorageServices and StorageSystems can be edited, but the writeable properties of objects under other resources cannot be edited.

**Comment by rahlvers** [comment]
Needs additional verification for Redfish objects.

**Comment by ddeel** [comment]
Running with the latest emulator code (Swordfish-26thjune branch), it looks like the most recent version of the Basic Web Client (SNIA-basic-web-clinet-#30 branch) is able to update properties of dynamic objects that support PATCH operations for the property being updated. This appears to be true for Redfish objects as well as swordfish objects, but more testing should be done.
