### ISSUE TITLE
Notes / Enhancements for the User Guide

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-basic-web-client#27]
- [x]  First sentence needs to be completely rewritten.  This is a "How", not a what.  (SNIA basic Web Client organizes collection’s data in a blade interface by elaborating it into 3 sections),   The User doesn't care about this - they care about "Manage Swordfish systems".

- [x] Section 3 - Install 3.1 #4 - None of us have ever installed Webstrom.

- [x]  Linux instructions?

- [x] Do installation instructions need to be here?  Refer to installation doc instead.

- [x]  Login.  Needs to be clarified to be login to the web client itself.  Also Change text here to say this is the default, may be changed by the implementation.

- [x] "Process Engine" - Change to "Using the Swordfish Web Client"

- [x] IP address instructions need to include directions for port number.

- [x] Combine images with text describing the functionality.

- [x] Make add / delete service a major section.

- [x] Remove batch commands (install instructions)

**Comment by sravanthikalluri19** [comment]
Added instruction on how to install and environment set up for linux environment

**Comment by rahlvers** [comment]
Note user guide updates - respond to comments in updated word doc in SNIA-basic-webclient-docs branch.
