### ISSUE TITLE
Does not remove items in Redfish collections

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-basic-web-client#29]
When you click on "Remove" for a StorageService collection or a StorageSystems collection, you are able to successfully remove an item by clicking on the minus sign ("-"), and the client responds with an alert saying "Deleted Sucessfully".

When you click on "Remove" for any of the Redfish collections (Chassis, Managers, Systems, etc) and try to do the same thing, it fails to remove the item and the client responds with an alert saying "Deleting a service Failed".

This can be reproduced by using the client with the Swordfish API Emulator running in its default configuration.

**Comment by sravanthikalluri19** [comment]
@ddeel it might be  because of the delete request to the Redfish API has stopped running or the url doesn't exist.
could you please test the same operation either in POSTMAN or REST CLIENT

**Comment by ddeel** [comment]
To replicate an example of the problem, start the client, open an instance of a Swordfish Service running on the emulator in its default configuration, look at "Chassis" in that instance, and click on the "Remove" button:
![image](https://user-images.githubusercontent.com/16329575/40004869-7a6b8b2a-574b-11e8-991e-c22433b471f3.png)

Now click on the minus sign next to "Chassis-12" and the following alert comes up:
![image](https://user-images.githubusercontent.com/16329575/40005049-f3fff4da-574b-11e8-86d1-5d4685f702db.png)

If you then click on "OK" in the alert, the resource has not been removed:
![image](https://user-images.githubusercontent.com/16329575/40005285-66a86490-574c-11e8-9031-aafde226b88c.png)

If you send the following DELETE command using the Restlet Client, the resource is properly deleted:
![image](https://user-images.githubusercontent.com/16329575/40005394-ac738130-574c-11e8-9687-f27babf60ec7.png)

After deleting "Chassis-12" with the Restlet Client, the Swordfish Basic Web Client shows that it has been deleted from the Chassis collection:
![image](https://user-images.githubusercontent.com/16329575/40005520-f3553b3e-574c-11e8-9cf9-f5c3487b8155.png)

The Restlet Client is able to delete resources in the Chassis collection, but the client is not able to do this. The problem is also present for the Managers collection and the Systems collection, and possibly others.

**Comment by sravanthikalluri19** [comment]
We will find the RCA for it and update the code to resolve the bug in basic web client
