### ISSUE TITLE
Does not add items to Redfish collections

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-basic-web-client#30]
When you click on "Add" for a StorageService collection or a StorageSystem collection, you are able to successfully add an item by entering the name of the new item and clicking on the Add button.

When you click on "Add" for any of the Redfish collections (Chassis, Managers, Systems, etc) and try to do the same thing, it initially appears to add the new item, but the new item does not behave correctly.

If you click on the new item, a new panel appears that says:
    Your Connection was interpreted with following
    Status Code : 404
    Error : Not Found

If you click on a different collection and then come back to the collection where the new item had been added, the new item is no longer there.

This can be reproduced by using the client with the Swordfish API Emulator running in its default configuration.

**Comment by sravanthikalluri19** [comment]
@ddeel it might be because of the Add request to the Redfish API has stopped running or the url doesn't exist.
could you please test the same operation either in POSTMAN or REST CLIENT

**Comment by ddeel** [comment]
Please try adding a resource to the "Systems" collection for an example of the problem.

Start the client, open an instance of a Swordfish Service running on the emulator in its default configuration, look at the "Systems" collection in that instance, click on the "Add" button, and enter the name of a new system ("NewSystem"):
![image](https://user-images.githubusercontent.com/16329575/40006685-df351388-574f-11e8-942a-4bee1e3ec6d4.png)

Click on the "Add" button in the "Add to Collection" panel:
![image](https://user-images.githubusercontent.com/16329575/40006814-2cb083ae-5750-11e8-937b-c7c032295d57.png)

"NewSystem" appears to have been added to the "Systems" collection, but if you click on it, you see this:
![image](https://user-images.githubusercontent.com/16329575/40006915-6586a910-5750-11e8-90b9-2e6caa62d943.png)

If you then click on some other collection in the "Explore The Resources" panel and then click again on the "Systems" collection in the "Explore The Resources" panel, you see that the "NewSystem" resource is no longer there:
![image](https://user-images.githubusercontent.com/16329575/40007075-bdb4877e-5750-11e8-9aca-b2aacb502104.png)

This is not proper behavior.

**Comment by sravanthikalluri19** [comment]
@ddeel i tried with the Systems 
1)  Existing Systems Service collections
![image](https://user-images.githubusercontent.com/33854700/40035229-6ef822c0-581e-11e8-9656-d6eb36dd28ea.png)
2) Tried to add a new collection
![image](https://user-images.githubusercontent.com/33854700/40035276-99c31e88-581e-11e8-9513-6cc8b9753c0a.png)
3) An alert with the status of the add operation is displayed even before adding to the collection list
![image](https://user-images.githubusercontent.com/33854700/40035314-c3aa76f6-581e-11e8-9260-28fe70d8153c.png)

Don, please try to rebuild the web client and let us know if still the issue exists
Steps to rebuild:
1. cd views && ng build
2. cd.. && npm start

**Comment by ddeel** [comment]
The issue still exists. Attempting to add a new member to the "Systems" collection still behaves as described above. The new system is shown after the Add operation, but clicking on the newly-added system gets a status code 404 error. The newly-added system also still disappears if you click on some other collection (like the "Chassis" collection) and then click on the "Systems" collection again.

I am working with the latest versions of the code for the Swordfish emulator and the Swordfish Basic Web Client. Both are running on Windows, and the client has just been rebuilt.

**Comment by sravanthikalluri19** [comment]
@ddeel I tested again but unable to reproduce the issue
adding a collection to the existing  collection list depends on the status code of the api response
please find the below code snippet.

![image](https://user-images.githubusercontent.com/33854700/40953526-bcc3e446-689d-11e8-91bc-fd498b524d36.png)


please test the api results in either postman or rest client and let us know if u are able to add the collection successfully

**Comment by rahlvers** [comment]
@anandnagraj - We are running into issues that may be related to the emulator.  Any way you could try out the difference on your system between Redfish and Swordfish type components to see if you see the issue?

**Comment by rahlvers** [comment]
I tried the add button on a Redfish resource collection and I can see that a POST command is issued to the <URI of the collection>/<Name>  by the basic web client. However,  request body is empty and the server failed the request.  The request also is not issued on the URI of the collection. It is at the URI of the resource which needs to be added.

Regards,
Anand

**Comment by rahlvers** [comment]
The server prints the entire request upon receiving it. The following URI was seen with the collection URI along with the name which was entered in the Name editbox. 
::ffff:10.180.120.207 - - [21/Jun/2018:21:41:45 +0000] "POST /redfish/v1/Chassis/0000000450123456789ABC000001 HTTP/1.1" 400 11 "-" "-"

The request body is the last parameter which was NULL and therefore not printed. 

Regards,
Anand
![screenshot](https://user-images.githubusercontent.com/13662743/41736210-170929fe-7549-11e8-8fe2-4bc900d393c7.jpg)

**Comment by sravanthikalluri19** [comment]
@rahlvers if possible can you please provide the skeleton of the POST request or a working sample example that is performed using REST client or postman

**Comment by ddeel** [comment]
There are two cases to be aware of for using a POST command to add a new resource to a resource collection. The first case must work with all server implementations, and the second case is a special situation that is only expected to work with the emulator.

--------

The first case is one that all Redfish/Swordfish server implementations must support, where a POST command with a JSON description of the new resource in the request body is sent to the top of a resource collection. Here is an example (xxxxxxxxxxx is an IP address and pppp is a port number):

Command:  POST xxxxxxxxxxx:pppp/redfish/v1/Chassis
Body:
{
"@odata.context": "/redfish/v1/$metadata#Chassis.Chassis",
"@odata.id": "/redfish/v1/Chassis/Chassis-15",
"@odata.type": "#Chassis.v1_0_0.Chassis",
"Id": "Chassis-15",
"Name": "New Chassis-15 object added to Chassis collection",
"ChassisType": "RackMount",
"Manufacturer": "Emulator of Redfish/Swordfish Computers",
"Model": "3500RX",
"SKU": "8675309",
"SerialNumber": "THX1138",
"Version": "1.02",
"PartNumber": "224071-J23",
"AssetTag": "Chicago-45Z-2381",
"Status":{
"State": "Enabled",
"Health": "OK"
},
"Thermal":{
"@odata.id": "/redfish/v1/Chassis/Chassis-15/Thermal"
},
"Power":{
"@odata.id": "/redfish/v1/Chassis/Chassis-15/Power"
},
"Links":{
"ComputerSystems":[],
"ResourceBlocks":[
{
"@odata.id": "/redfish/v1/CompositionService/ResourceBlocks/Block-10"
}
],
"ManagedBy":[
{
"@odata.id": "/redfish/v1/Managers/BMC-10"
}
]
}
}

When this POST command is received by a server implementation (including the emulator), the JSON description in the request body is used to create a new object in the Chassis collection. Implementations may check the JSON for correctness, so the JSON description in the request body needs to satisfy the requirements of Redfish/Swordfish schema.

--------

The second case is a special situation that is only expected to work with the emulator, where a POST command with an empty request body is sent to a named new element in a resource collection. Here is an example (xxxxxxxxxxx is an IP address and pppp is a port number):

Command:  POST xxxxxxxxxxx:pppp/redfish/v1/Chassis/NewName
Body:     <empty>

When this POST operation is received by the emulator, the emulator uses template information to create a default new object named "NewName" in the Chassis collection.

NOTE: The Redfish Interface Emulator still requires some code fixes, so this second case does not yet work correctly for some of the Redfish collections.

--------
