### ISSUE TITLE
Basic Web Client hangs when accessing a particular Volume under StorageServices

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-basic-web-client#34]
Running with the latest code for both the emulator and the client, the client hangs permanently when attempting to access one of the Volumes under StorageServices. This particular Volume is one of the Swordfish objects that is currently present by default whenever the emulator is started.

Here is the object trail, copied from the top of the Basic Web Client screen:
SAE180627  > StorageServices  > 1  > Volumes  > 61001234876545676100123487654567

The same thing happens when accessing a different emulator running on a different system. When the hang occurs, the only way to get the client to fully recover is to close the browser tab and restart the client in a different browser tab.

There might be something wrong with this particular Swordfish object in the emulator, but it seems like the client should time out after a few seconds and continue running without hanging.

**Comment by sravanthikalluri19** [comment]
Fixed as a part of new commit.
