### ISSUE TITLE
Fails to report a 405 "Method not allowed" error situation

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-basic-web-client#35]
The client appears to make a change (one that cannot succeed), and fails to report a 405 "Method Not Allowed" error situation.

Here is a sequence that shows the issue. The images below are from the current versions of the client and the emulator.

Initial state; shows the StorageServices collection:
![image](https://user-images.githubusercontent.com/16329575/42662075-10ba3c12-85e5-11e8-8dff-ea291345ac5f.png)

Editing the collection "Name" property to say "ChangedName":
![image](https://user-images.githubusercontent.com/16329575/42662102-2b8dfc04-85e5-11e8-8e68-031a136592b1.png)

The change appears to have been accepted without any error after clicking on the Save icon:
![image](https://user-images.githubusercontent.com/16329575/42662117-3e6a3932-85e5-11e8-860b-9d627c0fb443.png)

Clicking on a different resource (Chassis):
![image](https://user-images.githubusercontent.com/16329575/42662127-4f68da90-85e5-11e8-873f-32c861307bc8.png)

Go back to StorageServices and see that the collection's Name property was not actually changed, because it now says "Storage Service Collection" again, instead of "ChangedName":
![image](https://user-images.githubusercontent.com/16329575/42662160-6b8ab0ea-85e5-11e8-9bec-521d51ae2ec0.png)

This is what happens when the Chrome Restlet tool is used to attempt to PATCH the Name property on the StorageServices collection:
![image](https://user-images.githubusercontent.com/16329575/42662185-81192752-85e5-11e8-845d-093c388e7a28.png)

The issue is that the client is not reporting the 405 "Method Not Allowed" error, and it looks like the operation succeeded, when it has actually failed. The user only discovers the problem by going to a different resource (like Chassis) and then returning to the StorageServices collection.

Note that the client shows this same behavior this for ALL of the Redfish and Swordfish collections, not just the StorageServices collection.

**Comment by sravanthikalluri19** [comment]
1.Are there any pop-up errors implemented in the web client? 
Yes @rahlvers . Error messages are shown in the alert boxes.
2.Any errors coming from services should be passed through to the end user.
Only few service calls are sending the error message's as a response according to my observation.

We will look into the issue and update .

**Comment by ddeel** [comment]
Note that the Redfish Interface Emulator master branch was updated last Thursday. Any testing of the client should be done with an updated version of the Swordfish API Emulator that is based upon the updated Redfish Interface Emulator.

Running with an updated Swordfish API Emulator, I still see exactly the same problem that is being reported above.
