### ISSUE TITLE
Swordfish services previously added, needs a mechanism to authenticate when the application is relaunched  

### ISSUE THREAD

**Issue by anandnagraj** [SNIA/Swordfish-basic-web-client#6]
Description: When there are Swordfish services added to the basic web client which allow access based on authentication, upon re-launch of the application/web page, there is currently no mechanism for the user to enter credentials. As a result, subsequent operations fail because a session has not been established. 

Workaround: Delete the previous instance of Swordfish service which persisted across the re-launch and add it again.

**Comment by rahlvers** [comment]
Fixed in pull #10
