### ISSUE TITLE
The web client hangs when a resource is accessed

### ISSUE THREAD

**Issue by anandnagraj** [SNIA/Swordfish-basic-web-client#7]
Description: When a resource such as StorageSystem, Drive, Volume is accessed, the web client hangs up. Things are fine with collections though.

![image](https://user-images.githubusercontent.com/15414496/34510539-a4ba2932-f07a-11e7-8c4e-90d6c30d8e56.png)

**Comment by rahlvers** [comment]
Is this still an issue?

**Comment by ddeel** [comment]
@anandnagraj  - Does this problem still happen, or can this Issue be closed?

**Comment by rahlvers** [comment]
Per @anandnagraj - closing.
